# Docs for the Azure Web Apps Deploy action: 
# https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: 
# https://github.com/Azure/actions
# More info on Python, GitHub Actions, and 
# Azure App Service: https://aka.ms/python-webapps-actions

name: Continuous Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          envkey_POSTGRES_TEST_URL: ${{ secrets.POSTGRES_TEST_URL }}
          envkey_JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          envkey_FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          file_name: .env
    
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'GoPodcastAPI'
          slot-name: 'Production'
          publish-profile: 
            ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_47BD876E8B804CAE99183DD431C3F529 }}
